name: Release

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://npm.pkg.github.com'

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |-
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PACKAGES_TOKEN }}" >> ~/.npmrc
          npm ci
          rm -rf ~/.npmrc

      - name: Build package
        run: |-
          npm run build

      - name: Prepare release
        run: |-
          cp package.json LICENSE README.md build/
          cd build
          sed -i -e "s~\"version\": \"0.0.0-dev\"~\"version\": \"${GITHUB_REF##*/}\"~" package.json

      - name: Publish pre-release to NPM
        if: ${{ github.event.release.prerelease }}
        run: |-
          cd build
          npm publish --tag next
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release to NPM
        if: ${{ !github.event.release.prerelease }}
        run: |-
          cd build
          npm publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
